Paul：网页js逻辑执行顺序修改
FeixiDev/flask_demo pull request #2
Opened 2020-09-18 02:35 UTC by mattie-feng

2020-09-18 04:59 UTC, userhei requested changes
心累

2020-09-18 04:59 UTC, userhei commented on manage/manage.py
> +IP_LIS = ['10.203.1.223', '10.203.1.224']
？？？我有强迫症，你们不知道？

2020-09-18 04:59 UTC, userhei commented on manage/manage.py
> +@app.route('/get_master_ip', methods=['GET', 'POST'])
这个路由 叫 master_ip比较好，访问这个路由从而得到IP的模块 叫 get_xxx比较好。

2020-09-18 04:59 UTC, userhei commented on manage/manage.py
> +    return jsonify(IP_LIS[0])
？？？

2020-09-18 04:59 UTC, userhei commented on manage/manage.py
> +        http = urllib3.PoolManager()
不是说过这个放在外面吗？

2020-09-18 04:59 UTC, userhei commented on manage/manage.py
> +        http = urllib3.PoolManager()
这种事情是需要说多少遍？

2020-09-18 04:59 UTC, userhei commented on manage/templates/index.html
> +			const ip = data;
怪怪。。。你参数直接叫ip，不行呀？

2020-09-18 04:59 UTC, userhei commented on manage/templates/index.html
> +			});
这部分可以
function get_cmd_result() {
 	$.ajax({
定义一个函数的吧？？

2020-09-18 04:59 UTC, userhei commented on manage/templates/index.html
> +			<input type="submit" value="查看数据" onclick="see_cmd_result()">
别 onclick了，就直接显示。。。see。。。。

see。。。。
Mattie，你帮帮Paul呀

2020-09-18 04:59 UTC, userhei commented on manage/templates/login.html
> +            <p >数据接口登录失败！</p>
登录 不应该是用户名和密码登录吗？

2020-09-18 04:59 UTC, userhei commented on manage/templates/login.html
> +            <p >数据接口登录失败！</p>
这了说的登录不是Ethan 说的什么数据接口登录，这里登录就是用户 密码 登录

2020-09-18 04:59 UTC, userhei commented on manage/templates/login.html
> +            <p >数据接口登录失败！</p>
登录成功之后，就有 cookie 还是 session 什么东西来保证操作是在有登陆的情况下进行

2020-09-18 04:59 UTC, userhei commented on vplx/vplx.py
> +data = ['']
？？

2020-09-21 03:13 UTC, mattie-feng commented on vplx/vplx.py
> +
还是要有两个路由
* 调用函数路由：接收前端数据并且返回一个状态值（是否成功接收到数据）
* 数据路由：return {"add":x+y,"subtract":x-y,"multiply":x*y,"divided":x/y}
不需要使用到DATA_PROCESSING全局变量

2020-09-23 07:40 UTC, closed without merging